---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: stress-test
  name: stress-test
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: stress-ng
  namespace: stress-test